### ISSUE TITLE
Falling Blocks

### ISSUE THREAD

**Issue by TannerJL** [kvertner/deathflamingo#3]
Grass, stone and wood blocks do not animate for me when the "End Turn" button is pushed. The bridges do animate. The blocks that don't animate just disappear after the animation is finished. I know this isn't an issue on Kim's PC so I'm not sure what's wrong.

**Comment by kvertner** [comment]
@TannerJL Assigning this back to you.  I think the issue was that you were using objects that did not have the cube script assigned to them.  In the future, be sure to create a prefab in your Tanners Prefab folder, add the cube script (set the values to match other objects with respect to the crumble logic) and then build away.  If you are still seeing this on some levels, let me know which ones and I can take a look again.

**Comment by TannerJL** [comment]
@kvertner They already have the cube script.

**Comment by kvertner** [comment]
@TannerJL Does this happen on all levels?  If not, let me know which level(s) you see this on and I can dig in a little more.

**Comment by TannerJL** [comment]
This happens on all levels for me.

[20230209_161204.zip](https://github.com/kvertner/deathflamingo/files/10702635/20230209_161204.zip)

**Comment by TannerJL** [comment]
Its not a big issue as long as its not part of how it builds.

**Comment by kvertner** [comment]
We determined that the object that were not responding to the script had "static" enabled.
